
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;
import java.awt.BorderLayout;  
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elify
 */
public class AllCandidates extends javax.swing.JFrame {

    /**
     * Creates new form AllCandidates
     */
     PartySelection b = new PartySelection();

      ArrayList AllCandidates  = b.getAllCand();
      
      
      public AllCandidates() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("flagicon.png")));
        ui.setBorder(new EmptyBorder(4,4,4,4));
        setContentPane(ui);
        
        boxes = new JCheckBox[AllCandidates.size()];


        JButton votebutton=new JButton("VOTE");  
        votebutton.setBounds(30,10,10,30);  
        ui.add(votebutton); 
          for (int i = 0; i < AllCandidates.size(); i++) {
            createrCheckBox(i);
         Font newCheckBoxFont=new Font(boxes[i].getFont().getName(),boxes[i].getFont().getStyle(),10);  
         boxes[i].setFont(newCheckBoxFont);  

        }
          
      
                  
                  
                  
                  
  votebutton.addActionListener(new ActionListener() {
         
   public void actionPerformed(java.awt.event.ActionEvent e) {
        JOptionPane.showMessageDialog(rootPane,"Voted!");
        MainWindow newframe = new MainWindow();
        newframe.setVisible(true);
   
        try {
           FileWriter file = new FileWriter("AllCandvote.txt",true);
         
            for (int i = 0; i < AllCandidates.size(); i++) {
                if(boxes[i].isSelected()){
                file.write(boxes[i].getText()+"\n");
                }
            }
            file.close();
        } 
    catch (IOException evt) {
        evt.printStackTrace();
    }
    
   } });
        setTitle("All Candidates");
        pack();
            ui.setPreferredSize(ui.getPreferredSize());

        setVisible(true);
        setResizable(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
              try {
          WriteFile();
      } catch (IOException ex) {
          Logger.getLogger(EqualityFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
 
 
 JPanel ui= new JPanel(new GridLayout(0,5));
 
    private JCheckBox boxes[];


    public void createrCheckBox(int i) {
        boxes[i] = new JCheckBox();
        boxes[i].setBorder(new EmptyBorder(5,10,10,5));       
            boxes[i].setText((String) AllCandidates.get(i));
                        boxes[i].setPreferredSize(boxes[i].getPreferredSize());

            boxes[i].setSelected(false);
            boxes[i].setVisible(true);
            ui.add(boxes[i]);
    }
 public void WriteFile() throws IOException{
     
     try{
     FileWriter f = new FileWriter("Labourcand.txt",true);
     Writer  output = new BufferedWriter(f);
     int sz = AllCandidates.size();
     for(int i=0 ; i<sz ; i++){
         output.write(AllCandidates.get(i).toString()+"\n");
         
     }
     output.close();
     }
     catch(Exception e){
         JOptionPane.showMessageDialog(null,"I cannot create that file.");
     }
     
 }
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCandidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         Runnable r = () -> {
            JFrame frame = new AllCandidates();
           frame.setSize(2000,2000);  

        };
        SwingUtilities.invokeLater(r);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
