import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elify
 */
public class CandidateStatistics extends javax.swing.JFrame {

    /**
     * Creates new form CandidateElectionSurveyStatistics
     */
    /*
     PartySelection b = new PartySelection();

      ArrayList Equality = b.getEquality();
      ArrayList Felicity = b.getFelicity();
      ArrayList Freedom = b.getFreedom();
      ArrayList Labour = b.getLabour();
      ArrayList ModernLiberation = b.getModernLiberation();
      ArrayList NationalPeople = b.getNationalPeople();
      ArrayList NewDemocratic = b.getNewDemocratic();
      ArrayList NewNature = b.getNewNature();
      ArrayList PeopleAction = b.getPeopleAction();
      ArrayList Republican = b.getRepublicanPeople();
      ArrayList Workers = b.getUnitedWorkers();
      ArrayList Left = b.getUniversalLeft();
*/
     ArrayList candidates = new ArrayList();
   
private void readFile(ArrayList<String> candidates, String candidatestxt) throws FileNotFoundException {
        List<String> candidateList = new ArrayList<>(1000);
        Scanner fileInput = new Scanner(new File(candidatestxt));
        while (fileInput.hasNextLine()) {
            candidateList.add(fileInput.nextLine());
        }
        candidates.addAll(candidateList);

        
        
    }  
      
    public CandidateStatistics(String partyname , ArrayList arr) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("flagicon.png")));
       this.candidates=arr;
         JLabel lab1 = new JLabel();
        setTitle("Candidates Statistics");

       lab1.setText("GENERAL ELECTION SURVEY STATISTICS PARTY"+partyname+"Party");
  ui.setBorder(new EmptyBorder(30,30,30,30));
        setContentPane(ui);
        boxes = new JLabel[candidates.size()];

        for (int i = 0; i < candidates.size(); i++) {
            createrLabel(i);
        }
        JButton back=new JButton("BACK");  
        back.setBounds(30,10,10,30);  
        ui.add(back); 
          back.addActionListener(new ActionListener() {
         
   public void actionPerformed(java.awt.event.ActionEvent e) {
        GeneralStatistics newframe = new GeneralStatistics();
        newframe.setVisible(true);
   
        
    
   } });
        pack();
        setVisible(true);
        setResizable(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

   
    JPanel ui= new JPanel(new GridLayout(0,2));
 
    private JLabel boxes[];


    public void createrLabel(int i ) {
      
        boxes[i] =new JLabel((String) candidates.get(i)+":%3.57");
    
        boxes[i].setBorder(new EmptyBorder(0,28,0,0));
        ui.add(boxes[i]);  
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new CandidateStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
