


import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elify
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
   
    public MainWindow() {
        initComponents();
    l1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("pngwave.png")).getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH)));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("flagicon.png")));
        setTitle("Main Window");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindow = new javax.swing.JPanel();
        UpperPanel = new javax.swing.JPanel();
        GeneralElectionSurvey = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        seeResult = new javax.swing.JToggleButton();
        participate = new javax.swing.JToggleButton();
        exit = new javax.swing.JToggleButton();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWindow.setBackground(new java.awt.Color(204, 204, 204));
        mainWindow.setForeground(new java.awt.Color(255, 255, 255));
        mainWindow.setToolTipText("");

        UpperPanel.setBackground(new java.awt.Color(51, 153, 255));
        UpperPanel.setForeground(new java.awt.Color(204, 204, 204));

        GeneralElectionSurvey.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        GeneralElectionSurvey.setText("GENERAL ELECTION SURVEY");

        javax.swing.GroupLayout UpperPanelLayout = new javax.swing.GroupLayout(UpperPanel);
        UpperPanel.setLayout(UpperPanelLayout);
        UpperPanelLayout.setHorizontalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpperPanelLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(GeneralElectionSurvey)
                .addGap(219, 219, 219))
        );
        UpperPanelLayout.setVerticalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(GeneralElectionSurvey)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        question.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        question.setForeground(new java.awt.Color(102, 102, 102));
        question.setText("What would you like to do?");

        seeResult.setBackground(new java.awt.Color(76, 107, 232));
        seeResult.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        seeResult.setText("See Results");
        seeResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeResultActionPerformed(evt);
            }
        });

        participate.setBackground(new java.awt.Color(76, 107, 232));
        participate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        participate.setText("Participate");
        participate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participateActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(76, 107, 232));
        exit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(51, 51, 51));
        l1.setText("ELECTION OF REPUBLIC OF TURKEY");
        l1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout mainWindowLayout = new javax.swing.GroupLayout(mainWindow);
        mainWindow.setLayout(mainWindowLayout);
        mainWindowLayout.setHorizontalGroup(
            mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWindowLayout.createSequentialGroup()
                .addGroup(mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWindowLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(seeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(participate)
                        .addGap(79, 79, 79)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainWindowLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(UpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1)
                    .addComponent(question))
                .addGap(262, 262, 262))
        );
        mainWindowLayout.setVerticalGroup(
            mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWindowLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(UpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(l1)
                .addGap(115, 115, 115)
                .addComponent(question)
                .addGap(119, 119, 119)
                .addGroup(mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(participate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void seeResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeResultActionPerformed

        GeneralStatistics newframe = new GeneralStatistics();
        newframe.setVisible(true);
    }//GEN-LAST:event_seeResultActionPerformed

    private void participateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participateActionPerformed
        ParticipationWindow tempFrame = new ParticipationWindow();
        tempFrame.setVisible(true);
    }//GEN-LAST:event_participateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
 
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
     /*    ImageIcon image = new ImageIcon("turkey.png");
JLabel label = new JLabel("", image, JLabel.CENTER);
JPanel panel = new JPanel(new BorderLayout());
panel.add( label, BorderLayout.CENTER );
        
        */
        
       
        
        
      
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GeneralElectionSurvey;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JToggleButton exit;
    private javax.swing.JLabel l1;
    private javax.swing.JPanel mainWindow;
    private javax.swing.JToggleButton participate;
    private javax.swing.JLabel question;
    private javax.swing.JToggleButton seeResult;
    // End of variables declaration//GEN-END:variables
}

/*
              REFERENCES
https://www.youtube.com/watch?v=nkM2DbbqHPY channel for set icon and image


*/