
import java.awt.Toolkit;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elify
 */
public class ParticipationWindow extends javax.swing.JFrame {

    /**
     * Creates new form ParticipationWindow
     */
    public ParticipationWindow() {
        
        initComponents();
                setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("flagicon.png")));
        setTitle("Participation Window");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        participantInformation = new javax.swing.JPanel();
        upperparticipant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        genderbox = new javax.swing.JComboBox<>();
        surnamefield = new javax.swing.JTextField();
        professionfield = new javax.swing.JTextField();
        educationbox = new javax.swing.JComboBox<>();
        mailadressfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        back4 = new javax.swing.JButton();
        continue4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        agefield1 = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        participantInformation.setBackground(new java.awt.Color(255, 255, 255));
        participantInformation.setForeground(new java.awt.Color(204, 204, 204));

        upperparticipant.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Participant Information");

        javax.swing.GroupLayout upperparticipantLayout = new javax.swing.GroupLayout(upperparticipant);
        upperparticipant.setLayout(upperparticipantLayout);
        upperparticipantLayout.setHorizontalGroup(
            upperparticipantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperparticipantLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        upperparticipantLayout.setVerticalGroup(
            upperparticipantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperparticipantLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Surname:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Age:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Profession:");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Education:");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contact Information");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Personal Information");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phone Number:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("E-mail Adress:");

        genderbox.setBackground(new java.awt.Color(204, 204, 204));
        genderbox.setForeground(new java.awt.Color(51, 51, 51));
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));

        surnamefield.setBackground(new java.awt.Color(204, 204, 204));
        surnamefield.setForeground(new java.awt.Color(51, 51, 51));

        professionfield.setBackground(new java.awt.Color(204, 204, 204));
        professionfield.setForeground(new java.awt.Color(51, 51, 51));

        educationbox.setBackground(new java.awt.Color(204, 204, 204));
        educationbox.setForeground(new java.awt.Color(51, 51, 51));
        educationbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primary School", "High School", "University", "Post-graduate", " " }));

        mailadressfield.setBackground(new java.awt.Color(204, 204, 204));
        mailadressfield.setForeground(new java.awt.Color(51, 51, 51));

        phonefield.setBackground(new java.awt.Color(204, 204, 204));
        phonefield.setForeground(new java.awt.Color(51, 51, 51));

        back4.setBackground(new java.awt.Color(0, 153, 255));
        back4.setText("Back");
        back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back4ActionPerformed(evt);
            }
        });

        continue4.setBackground(new java.awt.Color(0, 153, 255));
        continue4.setText("Continue");
        continue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue4ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Gender:");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Name:");

        agefield1.setBackground(new java.awt.Color(204, 204, 204));
        agefield1.setForeground(new java.awt.Color(51, 51, 51));

        namefield.setBackground(new java.awt.Color(204, 204, 204));
        namefield.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout participantInformationLayout = new javax.swing.GroupLayout(participantInformation);
        participantInformation.setLayout(participantInformationLayout);
        participantInformationLayout.setHorizontalGroup(
            participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(participantInformationLayout.createSequentialGroup()
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(participantInformationLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(participantInformationLayout.createSequentialGroup()
                                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phonefield, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(mailadressfield)))
                            .addComponent(jLabel7)
                            .addGroup(participantInformationLayout.createSequentialGroup()
                                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11))
                                .addGap(42, 42, 42)
                                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(professionfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(educationbox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(258, 258, 258))
                    .addGroup(participantInformationLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(upperparticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, participantInformationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(continue4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(back4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        participantInformationLayout.setVerticalGroup(
            participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(participantInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperparticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(namefield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(surnamefield))
                .addGap(8, 8, 8)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(agefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(professionfield, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(educationbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(participantInformationLayout.createSequentialGroup()
                        .addComponent(mailadressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(participantInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(continue4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(participantInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(participantInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue4ActionPerformed
       
       String name = namefield.getText().toString();
       String surname = surnamefield.getText().toString();
       String gender = genderbox.getSelectedItem().toString();
       String age = agefield1.getText().toString();
       String profession = professionfield.getText().toString();
       String education = educationbox.getSelectedItem().toString();
       String mail = mailadressfield.getText().toString();
       String phonenumber = phonefield.getText().toString();
       
       try{
           
           FileWriter writer = new FileWriter("personalinf.txt",true);
           writer.write(System.getProperty("line.separator"));
           writer.write(name);
           writer.write(System.getProperty("line.separator"));
           writer.write(surname);
           writer.write(System.getProperty("line.separator"));
           writer.write(gender);
           writer.write(System.getProperty("line.separator"));
           writer.write(age);
           writer.write(System.getProperty("line.separator"));
           writer.write(profession);
           writer.write(System.getProperty("line.separator"));
           writer.write(education);
           writer.write(System.getProperty("line.separator"));
           writer.write(mail);
           writer.write(System.getProperty("line.separator"));
           writer.write(phonenumber);
           writer.write(System.getProperty("line.separator"));
           writer.close();
       boolean nameCheck = name.isEmpty();
       boolean snameCheck = surname.isEmpty();
       boolean genderCheck = gender.isEmpty();
       boolean ageCheck = age.isEmpty();
       boolean professionCheck = profession.isEmpty();
       boolean educationCheck = education.isEmpty();
       boolean mailCheck = mail.isEmpty();
       boolean phonenumberCheck = phonenumber.isEmpty();
        
       if(nameCheck){
           JOptionPane.showMessageDialog(this,"Name field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(snameCheck){
           JOptionPane.showMessageDialog(this,"surname field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(genderCheck){
           JOptionPane.showMessageDialog(this,"Gender field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(ageCheck){
           JOptionPane.showMessageDialog(this,"Age field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(professionCheck){
           JOptionPane.showMessageDialog(this,"Profession field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(educationCheck){
           JOptionPane.showMessageDialog(this,"Education field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(mailCheck){
           JOptionPane.showMessageDialog(this,"Mail field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(phonenumberCheck){
           JOptionPane.showMessageDialog(this,"Phone number field is empty","Error",JOptionPane.ERROR_MESSAGE);
       }
       if(!nameCheck && !snameCheck && !genderCheck && !ageCheck && !professionCheck && !educationCheck && !mailCheck && !phonenumberCheck){
            JOptionPane.showMessageDialog(this,"Participant data is saved!","Success!",JOptionPane.INFORMATION_MESSAGE);
            PartySelection newframe = new PartySelection();
            newframe.setVisible(true);
        }           
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(rootPane,"Error!");
           
       }
      
       
    }//GEN-LAST:event_continue4ActionPerformed

    private void back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back4ActionPerformed

       MainWindow newframe = new MainWindow();
        newframe.setVisible(true);
    }//GEN-LAST:event_back4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield1;
    private javax.swing.JButton back4;
    private javax.swing.JButton continue4;
    private javax.swing.JComboBox<String> educationbox;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mailadressfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JPanel participantInformation;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField professionfield;
    private javax.swing.JTextField surnamefield;
    private javax.swing.JPanel upperparticipant;
    // End of variables declaration//GEN-END:variables
}



/*
I used check method from Alper Hoca's swing tutorial youtube video
*/